# Generated by Django 4.1 on 2022-09-01 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_options_remove_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permanent_email',
        ),
    ]
