# Generated by Django 4.1 on 2022-09-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_affiliation_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='pincode',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='state',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
