# Generated by Django 4.1 on 2022-09-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_affiliation_city_alter_affiliation_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
