# Generated by Django 4.1 on 2022-09-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
