# Generated by Django 4.1 on 2022-09-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific', '0003_remove_image_image_remove_project_shared_with_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='text',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Paper', 'Research Paper'), ('Thesis', 'Thesis')], default=0, max_length=16),
        ),
    ]
