# Generated by Django 4.1 on 2022-09-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific', '0004_remove_project_configuration_remove_project_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.CharField(choices=[('txt', 'Text'), ('prop', 'Properties'), ('head', 'Header'), ('eqn', 'Equation'), ('img', 'Image'), ('tab', 'Table'), ('algo', 'Algorithm'), ('bib', 'Bibliography')], default='txt', max_length=4),
        ),
    ]
