# Generated by Django 4.1 on 2022-09-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific', '0006_delete_image_alter_project_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='date_uploaded',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='part',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
