# Generated by Django 4.1 on 2022-09-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific', '0007_rename_date_uploaded_part_date_created_part_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('order', 'label')},
        ),
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.CharField(choices=[('txt', 'Text'), ('prop', 'Properties'), ('head', 'Header'), ('eqn', 'Equation'), ('img', 'Image'), ('tab', 'Table'), ('algo', 'Algorithm'), ('bib', 'Bibliography'), ('tool', 'Toolbar')], default='txt', max_length=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('self', 'Self'), ('paper', 'Research Paper'), ('thesis', 'Thesis')], default=0, max_length=16),
        ),
    ]
