# Generated by Django 4.1 on 2022-09-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific', '0008_alter_part_options_alter_part_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.CharField(choices=[('text', 'Text'), ('properties', 'Properties'), ('outline', 'Section'), ('equation', 'Equation'), ('image', 'Image'), ('table', 'Table'), ('algorithm', 'Algorithm'), ('bibliography', 'Bibliography'), ('tool', 'Toolbar')], default='txt', max_length=16),
        ),
    ]
