# Generated by Django 4.0.6 on 2022-08-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_toolbars'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='cheldrens',
            field=models.TextField(blank=True, null=True),
        ),
    ]
