# Generated by Django 4.0.6 on 2022-08-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_section_cheldrens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('title',)},
        ),
        migrations.RenameField(
            model_name='section',
            old_name='cheldrens',
            new_name='childrens',
        ),
    ]
