# Generated by Django 4.0.6 on 2022-08-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='configuration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
