# Generated by Django 4.0.6 on 2022-08-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0005_section_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='type',
        ),
        migrations.AddField(
            model_name='section',
            name='category',
            field=models.IntegerField(choices=[(0, 'Paper'), (1, 'Thesis')], default=0),
        ),
    ]
