# Generated by Django 4.0.6 on 2022-08-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0006_remove_section_type_section_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='Project',
        ),
        migrations.DeleteModel(
            name='Toolbars',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
